### ISSUE TITLE
Installing EvaNE v0.3.2 

### ISSUE THREAD

**Issue by pandorica-opens** [Dru-Mara/EvalNE#14]
I am trying to install EvalNE v0.3.2 on python 3.6.12 on macOS and execute simple_example.py. 

While executing
`$conda install --file requirements.txt`

the output is

*error: numpy 1.15.1 is installed but numpy>=1.15.4 is required by {'pandas'}*

Basically, it can be reproduced by following the installation guide:

```shell
$git clone https://github.com/Dru-Mara/EvalNE.git
$cd EvalNE
$pip3 install -r requirements.txt
$sudo python3 setup.py install
```

or 

```shell
$git clone https://github.com/Dru-Mara/EvalNE.git
$cd EvalNE
$conda install --file requirements.txt
$sudo python3 setup.py install
```

By ignoring the error and later running 
```shell
$cd examples/
$python3 simple_example.py
```

we obtain

*evalne/utils/preprocess.py", line 523, in prep_graph G.remove_edges_from(G.selfloop_edges()) AttributeError: 'Graph' object has no attribute 'selfloop_edges'*

I think the issue is that we need to specify the versions in the requirements more clearly, i.e. the versions of scipy, pandas, tqdm and matplotlib.

**Comment by Dru-Mara** [comment]
Hello,

Thank you for the bug report. Indeed, there was an issue with the requirement specification. I have just pushed a fix that should solve it and tested the library again on Python 3.6.12 and 2.7.18.

Specifically, the issue was with numpy which should have required version 1.15.4 and networkx, which should have required exactly version 2.2 (the last version available for both python2 and python3)

Please let us know if you encounter any other issues.
