### ISSUE TITLE
Can we use EvalNE for multiplex embedding ?

### ISSUE THREAD

**Issue by LPioL** [Dru-Mara/EvalNE#3]
Hi,
Do you think your code can also be applied for the evaluation of heterogeneous and/or mutiplex network embedding ?

**Comment by Dru-Mara** [comment]
Hello,

The current version of the library can be used to evaluate heterogeneous networks since the nature of nodes and edges is irrelevant for our LP evaluation pipeline. In fact, one of the datasets used for testing the library is heterogeneous with nodes representing students, professors, courses, etc and the edges binary relations e.g student in course, prof teaches course, etc.

About the evaluation of multiplex networks, on the other hand, I can not guarantee that the library will work without some changes. Particularly because I assume the multiplex networks you refer to will contain multiple edges between the same pairs of nodes and this could cause some of the preprocessing functions as well as the train test split algorithms to fail.

Our future plans for extending the library currently do not include multiplex network evaluation, but if you want to implement this functionality we would be very happy to include your changes :)

Alex

**Comment by Dru-Mara** [comment]
Hello, 
The StundetDB dataset I tested the library on bundles in a single network: nodes representing professors, students, tracks etc. and edges representing the relations between these entities. If you can not generate a network like this form your data, or you want to treat specific relations differently, you can use the building blocks provided by the library and implement your own evaluation process. 
Alex
